### ISSUE TITLE
Grok pattern not defined

### ISSUE THREAD

**Issue by aligit** [swisscom/logstash-buildpack#4]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

CF version: 0
CF Cli: version 6.33.0+a345ea34d.2017-11-20

What version of the buildpack you are using?

If you were attempting to accomplish a task, what was it you were attempting to do?

I was trying to push my logstash buildpack(cf push) to CF through the following article:
[Building the ELK stack with our new Elasticsearch Enterprise](https://ict.swisscom.ch/2018/04/building-the-elk-stack-on-our-new-elasticsearch/)

What did you expect to happen?

To successfully push my logstash buildpack

What was the actual behavior?

I've got the following error: 
Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<Grok::PatternError: pattern %{CFPREFIX} not defined>

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by aligit** [comment]
found the fix here:
https://github.com/swisscom/logstash-buildpack/issues/4

**Comment by AndiBrunner** [comment]
Hi @aligit, thanks for reporting this issue. In fact, it seems that the cf-input-http template is not being delivered to the buildpack. Seems to be a manifest configuration issue. I will have a look at it. 

The other issue is in the blog https://ict.swisscom.ch/2018/04/building-the-elk-stack-on-our-new-elasticsearch/ : the name of the grok patterns directory should be "grok-patterns" and not "grokpatterns". (There are no naming restrictions for the files though) I'll contact @mkretz so he can fix this typo.

When this issue is fixed you are able to put all your grok patterns into the "grok-patterns" directory, including the one defining "CFPREFIX", and the logstash pipeline should work.

**Comment by AndiBrunner** [comment]
I had a look at it: when using the buildpack as an online buildpack (using the option "-b" with a git url, e.g. cf push -b https://github.com/swisscom/logstash-buildpack.git)  the cf-input-http template is delivered to the buildpack. I suppose the only issue you have is to put your grok patterns to a directory named "grok-patterns" instead of "grokpatterns". 

Nevertheless, the cf-input-http template is not delivered when using a system-buildpack (not relevant for you, just for documentation). I have to fix this.

**Comment by AndiBrunner** [comment]
I just saw it, you reported also to https://github.com/swisscom/cf-logstash-sample . Yes, the only issue seems to be the wrong naming of the directory in the article:  @aligit,  thx for sharing! I'm going to close this issue.
